# Generated by Django 3.1.1 on 2020-09-02 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No Title', max_length=20)),
                ('author', models.CharField(default='No name', max_length=30)),
                ('description', models.TextField(default='Null', max_length=500)),
                ('price', models.FloatField(default='Not on sale')),
                ('image1', models.ImageField(default='No images', upload_to='images/')),
                ('genre', multiselectfield.db.fields.MultiSelectField(choices=[('Biography', 'Biography'), ('Comic', 'Comic'), ('Crime', 'Crime'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('History', 'History'), ('Horror', 'Horror'), ('Poetry', 'Poetry'), ('Romance', 'Romance'), ('Mystery', 'Mystery')], default='No Choice', max_length=73)),
                ('post_date', models.DateField(blank=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
