# Generated by Django 3.1.1 on 2020-09-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_book_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='No name', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default='Null', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='No Title', max_length=50),
        ),
    ]
